// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.4
// source: interface.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "functionalist";

export interface UserMeta {
  id: number;
  displayName: string;
}

export interface FunctionalListMeta {
  id: number;
  displayName: string;
  description: string;
}

export interface FunctionalList {
  id: number;
  displayName: string;
  description: string;
  events: FunctionalListEvent[];
  users: UserMeta[];
}

export interface FunctionalListEvent {
  itemId: number;
  displayName?: string | undefined;
  checked?: boolean | undefined;
  /** Output only: the server always uses the receival time as the event time */
  occuredAt: number;
  userId: number;
}

export interface FunctionalListCreateRequest {
  displayName: string;
  description: string;
}

export interface FunctionalListUpdateRequest {
  id: number;
  displayName: string;
  description: string;
}

export interface FunctionalListListResponse {
  lists: FunctionalListMeta[];
}

export interface FunctionalListEventCreateRequest {
  itemId?: number | undefined;
  displayName?: string | undefined;
  checked?: boolean | undefined;
}

function createBaseUserMeta(): UserMeta {
  return { id: 0, displayName: "" };
}

export const UserMeta: MessageFns<UserMeta> = {
  encode(message: UserMeta, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.displayName !== "") {
      writer.uint32(18).string(message.displayName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserMeta {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserMeta();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserMeta {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      displayName: isSet(object.displayName)
        ? globalThis.String(object.displayName)
        : isSet(object.display_name)
          ? globalThis.String(object.display_name)
          : "",
    };
  },

  toJSON(message: UserMeta): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserMeta>, I>>(base?: I): UserMeta {
    return UserMeta.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserMeta>, I>>(object: I): UserMeta {
    const message = createBaseUserMeta();
    message.id = object.id ?? 0;
    message.displayName = object.displayName ?? "";
    return message;
  },
};

function createBaseFunctionalListMeta(): FunctionalListMeta {
  return { id: 0, displayName: "", description: "" };
}

export const FunctionalListMeta: MessageFns<FunctionalListMeta> = {
  encode(message: FunctionalListMeta, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.displayName !== "") {
      writer.uint32(18).string(message.displayName);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FunctionalListMeta {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFunctionalListMeta();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FunctionalListMeta {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      displayName: isSet(object.displayName)
        ? globalThis.String(object.displayName)
        : isSet(object.display_name)
          ? globalThis.String(object.display_name)
          : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
    };
  },

  toJSON(message: FunctionalListMeta): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FunctionalListMeta>, I>>(base?: I): FunctionalListMeta {
    return FunctionalListMeta.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FunctionalListMeta>, I>>(object: I): FunctionalListMeta {
    const message = createBaseFunctionalListMeta();
    message.id = object.id ?? 0;
    message.displayName = object.displayName ?? "";
    message.description = object.description ?? "";
    return message;
  },
};

function createBaseFunctionalList(): FunctionalList {
  return { id: 0, displayName: "", description: "", events: [], users: [] };
}

export const FunctionalList: MessageFns<FunctionalList> = {
  encode(message: FunctionalList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.displayName !== "") {
      writer.uint32(18).string(message.displayName);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    for (const v of message.events) {
      FunctionalListEvent.encode(v!, writer.uint32(82).fork()).join();
    }
    for (const v of message.users) {
      UserMeta.encode(v!, writer.uint32(90).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FunctionalList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFunctionalList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.events.push(FunctionalListEvent.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.users.push(UserMeta.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FunctionalList {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      displayName: isSet(object.displayName)
        ? globalThis.String(object.displayName)
        : isSet(object.display_name)
          ? globalThis.String(object.display_name)
          : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      events: globalThis.Array.isArray(object?.events)
        ? object.events.map((e: any) => FunctionalListEvent.fromJSON(e))
        : [],
      users: globalThis.Array.isArray(object?.users) ? object.users.map((e: any) => UserMeta.fromJSON(e)) : [],
    };
  },

  toJSON(message: FunctionalList): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.events?.length) {
      obj.events = message.events.map((e) => FunctionalListEvent.toJSON(e));
    }
    if (message.users?.length) {
      obj.users = message.users.map((e) => UserMeta.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FunctionalList>, I>>(base?: I): FunctionalList {
    return FunctionalList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FunctionalList>, I>>(object: I): FunctionalList {
    const message = createBaseFunctionalList();
    message.id = object.id ?? 0;
    message.displayName = object.displayName ?? "";
    message.description = object.description ?? "";
    message.events = object.events?.map((e) => FunctionalListEvent.fromPartial(e)) || [];
    message.users = object.users?.map((e) => UserMeta.fromPartial(e)) || [];
    return message;
  },
};

function createBaseFunctionalListEvent(): FunctionalListEvent {
  return {
    itemId: 0,
    displayName: undefined,
    checked: undefined,
    occuredAt: 0,
    userId: 0,
  };
}

export const FunctionalListEvent: MessageFns<FunctionalListEvent> = {
  encode(message: FunctionalListEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.itemId !== 0) {
      writer.uint32(8).int64(message.itemId);
    }
    if (message.displayName !== undefined) {
      writer.uint32(18).string(message.displayName);
    }
    if (message.checked !== undefined) {
      writer.uint32(24).bool(message.checked);
    }
    if (message.occuredAt !== 0) {
      writer.uint32(32).int64(message.occuredAt);
    }
    if (message.userId !== 0) {
      writer.uint32(40).int64(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FunctionalListEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFunctionalListEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.itemId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.checked = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.occuredAt = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.userId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FunctionalListEvent {
    return {
      itemId: isSet(object.itemId)
        ? globalThis.Number(object.itemId)
        : isSet(object.item_id)
          ? globalThis.Number(object.item_id)
          : 0,
      displayName: isSet(object.displayName)
        ? globalThis.String(object.displayName)
        : isSet(object.display_name)
          ? globalThis.String(object.display_name)
          : undefined,
      checked: isSet(object.checked) ? globalThis.Boolean(object.checked) : undefined,
      occuredAt: isSet(object.occuredAt)
        ? globalThis.Number(object.occuredAt)
        : isSet(object.occured_at)
          ? globalThis.Number(object.occured_at)
          : 0,
      userId: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
          ? globalThis.Number(object.user_id)
          : 0,
    };
  },

  toJSON(message: FunctionalListEvent): unknown {
    const obj: any = {};
    if (message.itemId !== 0) {
      obj.itemId = Math.round(message.itemId);
    }
    if (message.displayName !== undefined) {
      obj.displayName = message.displayName;
    }
    if (message.checked !== undefined) {
      obj.checked = message.checked;
    }
    if (message.occuredAt !== 0) {
      obj.occuredAt = Math.round(message.occuredAt);
    }
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FunctionalListEvent>, I>>(base?: I): FunctionalListEvent {
    return FunctionalListEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FunctionalListEvent>, I>>(object: I): FunctionalListEvent {
    const message = createBaseFunctionalListEvent();
    message.itemId = object.itemId ?? 0;
    message.displayName = object.displayName ?? undefined;
    message.checked = object.checked ?? undefined;
    message.occuredAt = object.occuredAt ?? 0;
    message.userId = object.userId ?? 0;
    return message;
  },
};

function createBaseFunctionalListCreateRequest(): FunctionalListCreateRequest {
  return { displayName: "", description: "" };
}

export const FunctionalListCreateRequest: MessageFns<FunctionalListCreateRequest> = {
  encode(message: FunctionalListCreateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.displayName !== "") {
      writer.uint32(18).string(message.displayName);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FunctionalListCreateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFunctionalListCreateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FunctionalListCreateRequest {
    return {
      displayName: isSet(object.displayName)
        ? globalThis.String(object.displayName)
        : isSet(object.display_name)
          ? globalThis.String(object.display_name)
          : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
    };
  },

  toJSON(message: FunctionalListCreateRequest): unknown {
    const obj: any = {};
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FunctionalListCreateRequest>, I>>(base?: I): FunctionalListCreateRequest {
    return FunctionalListCreateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FunctionalListCreateRequest>, I>>(object: I): FunctionalListCreateRequest {
    const message = createBaseFunctionalListCreateRequest();
    message.displayName = object.displayName ?? "";
    message.description = object.description ?? "";
    return message;
  },
};

function createBaseFunctionalListUpdateRequest(): FunctionalListUpdateRequest {
  return { id: 0, displayName: "", description: "" };
}

export const FunctionalListUpdateRequest: MessageFns<FunctionalListUpdateRequest> = {
  encode(message: FunctionalListUpdateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.displayName !== "") {
      writer.uint32(18).string(message.displayName);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FunctionalListUpdateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFunctionalListUpdateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FunctionalListUpdateRequest {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      displayName: isSet(object.displayName)
        ? globalThis.String(object.displayName)
        : isSet(object.display_name)
          ? globalThis.String(object.display_name)
          : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
    };
  },

  toJSON(message: FunctionalListUpdateRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FunctionalListUpdateRequest>, I>>(base?: I): FunctionalListUpdateRequest {
    return FunctionalListUpdateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FunctionalListUpdateRequest>, I>>(object: I): FunctionalListUpdateRequest {
    const message = createBaseFunctionalListUpdateRequest();
    message.id = object.id ?? 0;
    message.displayName = object.displayName ?? "";
    message.description = object.description ?? "";
    return message;
  },
};

function createBaseFunctionalListListResponse(): FunctionalListListResponse {
  return { lists: [] };
}

export const FunctionalListListResponse: MessageFns<FunctionalListListResponse> = {
  encode(message: FunctionalListListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.lists) {
      FunctionalListMeta.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FunctionalListListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFunctionalListListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.lists.push(FunctionalListMeta.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FunctionalListListResponse {
    return {
      lists: globalThis.Array.isArray(object?.lists)
        ? object.lists.map((e: any) => FunctionalListMeta.fromJSON(e))
        : [],
    };
  },

  toJSON(message: FunctionalListListResponse): unknown {
    const obj: any = {};
    if (message.lists?.length) {
      obj.lists = message.lists.map((e) => FunctionalListMeta.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FunctionalListListResponse>, I>>(base?: I): FunctionalListListResponse {
    return FunctionalListListResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FunctionalListListResponse>, I>>(object: I): FunctionalListListResponse {
    const message = createBaseFunctionalListListResponse();
    message.lists = object.lists?.map((e) => FunctionalListMeta.fromPartial(e)) || [];
    return message;
  },
};

function createBaseFunctionalListEventCreateRequest(): FunctionalListEventCreateRequest {
  return { itemId: undefined, displayName: undefined, checked: undefined };
}

export const FunctionalListEventCreateRequest: MessageFns<FunctionalListEventCreateRequest> = {
  encode(message: FunctionalListEventCreateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.itemId !== undefined) {
      writer.uint32(8).int64(message.itemId);
    }
    if (message.displayName !== undefined) {
      writer.uint32(18).string(message.displayName);
    }
    if (message.checked !== undefined) {
      writer.uint32(24).bool(message.checked);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FunctionalListEventCreateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFunctionalListEventCreateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.itemId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.checked = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FunctionalListEventCreateRequest {
    return {
      itemId: isSet(object.itemId)
        ? globalThis.Number(object.itemId)
        : isSet(object.item_id)
          ? globalThis.Number(object.item_id)
          : undefined,
      displayName: isSet(object.displayName)
        ? globalThis.String(object.displayName)
        : isSet(object.display_name)
          ? globalThis.String(object.display_name)
          : undefined,
      checked: isSet(object.checked) ? globalThis.Boolean(object.checked) : undefined,
    };
  },

  toJSON(message: FunctionalListEventCreateRequest): unknown {
    const obj: any = {};
    if (message.itemId !== undefined) {
      obj.itemId = Math.round(message.itemId);
    }
    if (message.displayName !== undefined) {
      obj.displayName = message.displayName;
    }
    if (message.checked !== undefined) {
      obj.checked = message.checked;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FunctionalListEventCreateRequest>, I>>(
    base?: I,
  ): FunctionalListEventCreateRequest {
    return FunctionalListEventCreateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FunctionalListEventCreateRequest>, I>>(
    object: I,
  ): FunctionalListEventCreateRequest {
    const message = createBaseFunctionalListEventCreateRequest();
    message.itemId = object.itemId ?? undefined;
    message.displayName = object.displayName ?? undefined;
    message.checked = object.checked ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
